version: '3'

services:
  funpay-cardinal:
    build: .
    container_name: funpay-cardinal
    volumes:
      - ./configs:/app/configs
      - ./logs:/app/logs
      - ./storage:/app/storage
      - ./plugins:/app/plugins
    restart: unless-stopped
    environment:
      - TZ=Europe/Moscow
